image: registry.gitlab.com/datek/docker-images/python3.9.2-poetry-pypi

stages:
  - test
  - publish

before_script:
  - echo $CI_COMMIT_BRANCH
  - echo $CI_COMMIT_TAG

test:
  stage: test
  script:
    - virtualenv venv
    - source venv/bin/activate
    - poetry install
    - pytest tests/
  artifacts:
    paths:
      - venv
    expire_in: 1 hour

publish:
  stage: publish
  dependencies:
    - test
  script:
    - source venv/bin/activate
    - poetry version ${CI_COMMIT_TAG}
    - poetry build
    - poetry publish -u __token__ -p $(cat /config/pypi_token)
  only:
      variables:
        - $CI_COMMIT_TAG != null
