name: CI Pipeline

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install env
        uses: ./.github/actions/install-python-env

      - name: Black
        run: |
          source .venv/bin/activate
          black datek_agar_core/ tests/ --check

      - name: Tests
        run: |
          source .venv/bin/activate
          pytest tests

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
